### PR TITLE
Update cache action runner

### LINKED ISSUE #253: Switch to actions/cache@v4
actions/cache@v4 was released a couple of weeks ago and moves to Node 20. Please update your reference to use the new version:
https://github.com/actions/cache/releases/tag/v4.0.0

## Description
When using composer-install I get this message:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

## Steps to reproduce
Run a workflow containing `composer-install`

## Expected behavior
Use latest version of actions/cache (v4)

## Screenshots or output
image

## Environment details
- version of this package: ramsey/composer-install@v2
- PHP version: 8.2
- OS: Linux (Ubuntu latest)

## Additional context
N/A

### PR DESCRIPTION
**Pull request by jrfnl**
## Description
The `actions/cache` package has released version 4.0 which updates the action runner to use Node 20.

Applying this fix gets rid of the following warning which is currently showing in the "Annotations" of workflows using the `ramsey/composer-install` action:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

Note: most action runners have published these types of update in a new major, so that seems to be the best practice. Not sure if this update warrants a new major for `ramsey/composer-install` ?

**Update**: **_From what I've read, I believe this should be released in a new major as otherwise people using this action in self-hosted runners will run into trouble with this change._**

Refs:
* https://github.com/actions/cache/releases/tag/v4.0.0
* https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

## Motivation and context
People don't like to see warnings in their workflows ;-)

## How has this been tested?
Pre-existing automated tests cover this change and the tests pass.

If you look in your own workflows, you can see that without this change, the following annotations (and a dozen more) display:
```
Run unclean (ubuntu-latest, v2)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Run action (ubuntu-latest, highest, v2, tests/fixtures/out-of-sync-lock)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

With this change, the annotations change to:
```
Run unclean (ubuntu-latest, v2)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Run action (ubuntu-latest, highest, v2, tests/fixtures/out-of-sync-lock)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

For this last warning regarding `actions/checkout@v3`, PR #248 is already open, so this is not addressed here.

## Types of changes

**_Not sure what to put here, could be seen as just plain maintenance, could also be seen as a breaking change ?_**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR checklist
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] I have added tests to cover my changes.

Fixes #253
Closes #254

### CODE REVIEW

**Comment by Levdbas** [comment]
@ramsey , would you like to take a look at this? We are getting a lot of deprecation notices at [@timber](https://github.com/timber/timber) that would be solved with this update.

**Comment by jrfnl** [comment]
@ramsey Any chance of movement on this PR ? 🙏🏻

**Comment by ruudk** [comment]
@ramsey Thanks for the merge, could you please tag it as well? We like to pin it to a specific version.

**Comment by jrfnl** [comment]
@ramsey Just saw the new tag - but shouldn't this have been a major release as per my comment above ?

> Note: most action runners have published these types of update in a new major, so that seems to be the best practice. Not sure if this update warrants a new major for `ramsey/composer-install` ?
> 
> **_Update: From what I've read, I believe this should be released in a new major as otherwise people using this action in self-hosted runners will run into trouble with this change._**

**Comment by ramsey** [comment]
Since the action is stand-alone, I didn't think it would cause BC issues. How will this affect users with self-hosted runners in a backwards incompatible way?

**Comment by jrfnl** [comment]
@ramsey self-hosted runners have their own self-hosted Node version(s) and the cache action now requiring Node 20 instead of Node 16 can break their build processes. Does that make it clearer ?

**Comment by ramsey** [comment]
Doh! Yes. That is clear. 🤦‍♂️

I'll take care of this later today. Sorry.

**Comment by jrfnl** [comment]
@ramsey No worries, I'm not on self-hosted myself ;-) Just thought I'd try and prevent you having to deal with lots of support issues.

You may want to pull the 2.3.0 release (or release a 2.3.1 without this particular change) to prevent people on self-hosted running into trouble .

**Comment by ramsey** [comment]
I'll release a 2.3.1 that removes that change and tag a 3.0.0 release with the change.

**Comment by jrfnl** [comment]
@ramsey Only just realized it's your birthday today... bit embarrassed I didn't start my earlier message with congratulations 🙈  Hope you had a great day and wishing you a lovely new year!

**Comment by ramsey** [comment]
Thanks! 😊

**Comment by Levdbas** [comment]
Hope you had a good day sir and thank you for your work! 🎉

**Comment by ramsey** [comment]
Due to BC issues, I have reverted the actions/cache upgrade in version 2.3.1 and have released 3.0.0, which includes the actions/cache upgrade. Please update your pinned versions to 3.0.0. See discussion on above, for more info.

**Pull request merged**
