### PR TITLE
Fix finding composer cache dir

### LINKED ISSUE #225: Cannot find composer.json
## Description

We are using this in github workflows with mono repo. Composer install can not find composer.json in sub-directories. Cache is empty.

## Steps to reproduce

    - uses: ramsey/composer-install@2.1.0
         with:
            working-directory: something
            composer-options: --prefer-dist

## Expected behavior

Should find composer.json and also create cache.

## Screenshots or output

[RuntimeException]                                               
File "./composer.json" cannot be found in the current directory  

## Environment details

- mono repo
- version of this package: *2.1.0*
- PHP version: *8.1*

## Additional context

Custom cache keys does not solve this problem.

### PR DESCRIPTION
**Pull request by TamasSzigeti**
## Description
Fix missing working dir when getting composer cache dir config
Bumping included composer.phar version to fix CI error – to the minimum that has this [fix](https://github.com/composer/composer/pull/10909)

## Motivation and context
Fixes #225

## How has this been tested?
Tested by manually running composer_paths.sh in a directory where there is no composer.lock
Current tests do not fail because there is another composer.lock in tests dir.
Added another test case, hope it works (:

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR checklist
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING.md** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by TamasSzigeti** [comment]
@ramsey Could you have a look, please?

**Comment by TamasSzigeti** [comment]
@ramsey Fixed the (unrelated) CI error before I noticed it is also done in #237 
This should be green now

**Comment by TamasSzigeti** [comment]
@ramsey Fixed conflict

**Comment by TamasSzigeti** [comment]
@ramsey Seems the v1 fail already happens in upstream branch, so this might be good to go?

**Comment by ramsey** [comment]
@TamasSzigeti Please update your branch with the latest upstream changes. Thanks!

**Comment by TamasSzigeti** [comment]
> @TamasSzigeti Please update your branch with the latest upstream changes. Thanks!

@ramsey Done

**Comment by TamasSzigeti** [comment]
@ramsey Adjusted the test for the changed github output

**Comment by TamasSzigeti** [comment]
@ramsey Is there anything yet to be done here?

**Comment by ramsey** [comment]
@TamasSzigeti Are you able to fix the test failures?

**Comment by TamasSzigeti** [comment]
@ramsey 
When it failed it was already failing in master, not coming from my changes. I rebased and will fix if it still fails

**Comment by petemcw** [comment]
Has there been any further progress on this? I can report that caching does not work correctly when using a "working-directory" input.

**Comment by mxr576** [comment]
Meh, I had just opened a duplicate in #247 before I found this :man_facepalming:

**Comment by mxr576** [comment]
Related issue: #246

**Comment by TamasSzigeti** [comment]
@mxr576 I totally forgot about this PR, maybe you could take it over, fix tests?

**Comment by mxr576** [comment]
> @mxr576 I totally forgot about this PR, maybe you could take it over, fix tests?

I cannot make any promises, tests were not executed on my PR because I am a first time contributor and I do not see failures due to: "The logs for this run have expired and are no longer available."

Rebasing/retriggering the build could be useful

**Comment by ramsey** [comment]
@mxr576 If you want to reopen your PR, I can click the button to allow the tests to run.

**Comment by mxr576** [comment]
Thanks, reopened

**Comment by TamasSzigeti** [comment]
@ramsey Sorry for taking this long, I fixed the tests, should be all green now.

**Comment by mxr576** [comment]
> @mxr576 I totally forgot about this PR, maybe you could take it over, fix tests?

Same here... ;S thx!!! \o/

**Review by ramsey — APPROVED** [review]

**Comment by ramsey** [comment]
Thank you!

**Pull request merged**
