### PR TITLE
feat: implement working-directory support, close #58

### LINKED ISSUE #58: Action will not work if composer.json is located in a sub dir
Hi, thanks for this amazing tool 👍 

This is my project strucure in short:
```
.github/workflows/ci.yaml
...
backend/composer.json
...
frontend/package.json
...
```

I tried using (`working-directory`, this is what other action use):
```yaml
            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                working-directory: "backend"
                with:
                    composer-options: "--no-scripts"
```

and:

```yaml
            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--no-scripts --working-dir=backend"
```

but this does not work 🤔  I don't have that much info:
CleanShot 2020-11-17 at 08 05 48

Thank you!

cc @localheinz

### PR DESCRIPTION
**Pull request by Kocal**
Hi @ramsey  :wave: 

This PR is a proposal for #58, I needed this action (really good job btw :+1:) to support working-directory since I use multiples composer.json on some projects.

For testing purposes, I've created a new directory `subdirectory` which contains a dependency to phpspec, and updated the CI to handle this directory too. Example of run (https://github.com/ramsey/composer-install/pull/93/checks?check_run_id=2013474145):
```
Run ./
  with:
    dependency-versions: lowest
    composer-options: --ignore-platform-reqs
    working-directory: subdirectory
Composer cache directory found at /home/runner/.cache/composer
Using lowest versions of dependencies
PHP version is 7.4.15
Cache primary key is php-7.4.15-subdirectory-lowest-96aa669351449a6f7700bf30687c1ab7f46133fb1e32af656eb3eb53b39dfc83---ignore-platform-reqs
Cache restore keys are: php-7.4.15-subdirectory-lowest-96aa669351449a6f7700bf30687c1ab7f46133fb1e32af656eb3eb53b39dfc83-, php-7.4.15-subdirectory-lowest-
/usr/local/bin/composer update --prefer-lowest --no-interaction --no-progress --ansi --working-dir=subdirectory --ignore-platform-reqs
Loading composer repositories with package information
Cache not found for input keys: php-7.4.15-subdirectory-lowest-96aa669351449a6f7700bf30687c1ab7f46133fb1e32af656eb3eb53b39dfc83---ignore-platform-reqs, php-7.4.15-subdirectory-lowest-96aa669351449a6f7700bf30687c1ab7f46133fb1e32af656eb3eb53b39dfc83-, php-7.4.15-subdirectory-lowest-
Updating dependencies
Lock file operations: 3 installs, 15 updates, 14 removals
  - Removing phpdocumentor/reflection-common (2.2.0)
  - Removing phpdocumentor/type-resolver (1.4.0)
  - Removing psr/container (1.0.0)
  - Removing psr/event-dispatcher (1.0.0)
  - Removing symfony/deprecation-contracts (v2.2.0)
  - Removing symfony/event-dispatcher-contracts (v2.2.0)
  - Removing symfony/polyfill-ctype (v1.22.1)
  - Removing symfony/polyfill-intl-grapheme (v1.22.1)
  - Removing symfony/polyfill-intl-normalizer (v1.22.1)
  - Removing symfony/polyfill-php73 (v1.22.1)
  - Removing symfony/polyfill-php80 (v1.22.1)
  - Removing symfony/service-contracts (v2.2.0)
  - Removing symfony/string (v5.2.3)
  - Removing webmozart/assert (1.9.1)
  - Locking dflydev/markdown (v1.0.0)
  - Downgrading doctrine/instantiator (1.4.0 => 1.0.5)
  - Downgrading phpdocumentor/reflection-docblock (5.2.2 => 2.0.0)
  - Downgrading phpspec/php-diff (v1.1.3 => v1.0.1)
  - Downgrading phpspec/phpspec (7.0.1 => 7.0.0)
  - Downgrading phpspec/prophecy (1.12.2 => 1.9.0)
  - Locking psr/log (1.0.0)
  - Downgrading sebastian/comparator (4.0.6 => 2.0.0)
  - Downgrading sebastian/diff (4.0.4 => 1.2.0)
  - Downgrading sebastian/exporter (4.0.3 => 3.0.0)
  - Downgrading sebastian/recursion-context (4.0.4 => 3.0.0)
  - Downgrading symfony/console (v5.2.3 => v3.4.0)
  - Locking symfony/debug (v2.8.0)
  - Downgrading symfony/event-dispatcher (v5.2.3 => v3.4.0)
  - Downgrading symfony/finder (v5.2.3 => v3.4.0)
  - Downgrading symfony/polyfill-mbstring (v1.22.1 => v1.0.0)
  - Downgrading symfony/process (v5.2.3 => v3.4.0)
  - Downgrading symfony/yaml (v5.2.3 => v3.4.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 18 installs, 0 updates, 0 removals
  - Downloading dflydev/markdown (v1.0.0)
  - Downloading symfony/yaml (v3.4.0)
  - Downloading symfony/process (v3.4.0)
  - Downloading symfony/finder (v3.4.0)
  - Downloading symfony/event-dispatcher (v3.4.0)
  - Downloading symfony/polyfill-mbstring (v1.0.0)
  - Downloading psr/log (1.0.0)
  - Downloading symfony/debug (v2.8.0)
  - Downloading symfony/console (v3.4.0)
  - Downloading sebastian/recursion-context (3.0.0)
  - Downloading sebastian/exporter (3.0.0)
  - Downloading sebastian/diff (1.2.0)
  - Downloading sebastian/comparator (2.0.0)
  - Downloading phpdocumentor/reflection-docblock (2.0.0)
  - Downloading doctrine/instantiator (1.0.5)
  - Downloading phpspec/prophecy (1.9.0)
  - Downloading phpspec/php-diff (v1.0.1)
  - Downloading phpspec/phpspec (7.0.0)
  - Installing dflydev/markdown (v1.0.0): Extracting archive
  - Installing symfony/yaml (v3.4.0): Extracting archive
  - Installing symfony/process (v3.4.0): Extracting archive
  - Installing symfony/finder (v3.4.0): Extracting archive
  - Installing symfony/event-dispatcher (v3.4.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.0.0): Extracting archive
  - Installing psr/log (1.0.0): Extracting archive
  - Installing symfony/debug (v2.8.0): Extracting archive
  - Installing symfony/console (v3.4.0): Extracting archive
  - Installing sebastian/recursion-context (3.0.0): Extracting archive
  - Installing sebastian/exporter (3.0.0): Extracting archive
  - Installing sebastian/diff (1.2.0): Extracting archive
  - Installing sebastian/comparator (2.0.0): Extracting archive
  - Installing phpdocumentor/reflection-docblock (2.0.0): Extracting archive
  - Installing doctrine/instantiator (1.0.5): Extracting archive
  - Installing phpspec/prophecy (1.9.0): Extracting archive
  - Installing phpspec/php-diff (v1.0.1): Extracting archive
  - Installing phpspec/phpspec (7.0.0): Extracting archive
Package dflydev/markdown is abandoned, you should avoid using it. Use michelf/php-markdown instead.
Generating autoload files
```

### CODE REVIEW

**Comment by OskarStark** [comment]
A lot of changed lines 😳

**Comment by Kocal** [comment]
Yeah this is mostly due to a new composer.lock and dist files that are commited 😄

**Comment by albe** [comment]
Great job :) Hopefully this can be merged

**Comment by ramsey** [comment]
Great work. Thank you for contributing! 🎉

**Comment by Kocal** [comment]
Thanks!

**Pull request merged**
