### PR TITLE
Put CI steps in hierarchical order in README

### PR DESCRIPTION
**Pull request by szepeviktor**
## Description
Don't encourage copy-pasters (people) to walk upside down.
## Motivation and context

hardware architecture ▶️ OS ▶️ services/server software (e.g. PHP) ▶️ development tools ▶️ dependencies ▶️ application

Please see https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/generic-php/gitignore.example

### CODE REVIEW

**Comment by ramsey** [comment]
I don't understand the relationship between the description, the link in the description, and the commit.

**Comment by szepeviktor** [comment]
> the description, the link in the description, and the commit

All three are hierarchical like a pyramid.
CI, gitignore files and other things could be ordered by this hierarchy.

- first things related to arch
- then OS-level stuff
- after that system software
- then development tools
- then dependencies
- finally things related to the application

I always go this way so because following rules are easy.

**Comment by szepeviktor** [comment]
In this case PHP is a system software, it lives much higher than the application's source code.

_Bad habits!_

**Comment by ramsey** [comment]
What’s wrong with alphabetical order, which I find easier to remember? 😁

**Comment by szepeviktor** [comment]
All right!
I leave it 100% up to you.

**Comment by ramsey** [comment]
I don’t necessarily disagree with you, but I prefer not having to think about what category things fall under, unless there’s a tool that can do it for me.

As for CI, I think checking out the repo is the appropriate first step, in case there’s anything in it that you need to run in order to configure the system.

**Comment by szepeviktor** [comment]
Okay.

**Pull request closed without merging**
