### PR TITLE
GH Actions: version update for codecov action runner

### PR DESCRIPTION
**Pull request by jrfnl**
## Description

Yet another predefined action has had a major release.

This is, again, mostly just a change of the Node version used by the action itself (from Node 12 to Node 16).

Refs:
* https://github.com/codecov/codecov-action/releases

---

@ramsey As an alternative to these kind of (manual) PRs, I'd be happy to add a Dependabot configuration which will create these type of PRs automatically.

## Motivation and context
General maintenance.

## How has this been tested?
Will automatically be tested via the GH Actions run.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR checklist
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ramsey** [comment]
> As an alternative to these kind of (manual) PRs, I'd be happy to add a Dependabot configuration which will create these type of PRs automatically.

Yes, please! 😄 

@Ocramius added this to ramsey/uuid, and I was going to try to see if it would work here, too, but I hadn't gotten to it, yet. I appreciate your help! https://github.com/ramsey/uuid/blob/4.x/.github/workflows/merge-dependabot-upgrades.yml

**Review by ramsey — APPROVED** [review]

**Comment by jrfnl** [comment]
@ramsey Looks like what @Ocramius added is not the actual configuration, but a way to automatically merge the pull requests from Dependabot. I'm a bit wary of automated merges, so let me for now just pull the config for you and then you can decide on the auto-merge workflow separately.

**Comment by jrfnl** [comment]
@ramsey See PR #227

**Comment by Ocramius** [comment]
> I'm a bit wary of automated merges,

Mostly depends on test confidence - not viable on some projects, but if you have a very detailed QA suite, you can do this.

**Comment by jrfnl** [comment]
@Ocramius Hear hear! Unfortunately the majority of projects I work on does not have that, so yeah.

**Pull request merged**
