### PR TITLE
chore: GH Actions: safeguard compatibility with Composer 1.x

### PR DESCRIPTION
**Pull request by jrfnl**
## Description
Safeguard compatibility with Composer 1.x by running both the `expect` tests as well as the integration test against both Composer 1.x as well as 2.x.

Related to #209.

Note: this is just a general test run to allow for discovering further incompatibilities. Depending what is decided about those, this PR will most likely need further adjustments.

## Motivation and context
* Composer 2 has only been out a year.
* As this tool is used in CI and projects may want to explicitly support Composer 1.x as well as 2.x in their code, so they will also want to test against both Composer majors.
* Not all Composer plugins have a Composer 2.x compatible version yet.

With that in mind, I believe it would be prudent to continue support for Composer 1.x (for the time being).

### CODE REVIEW

**Comment by ramsey** [comment]
I took the liberty of making some changes to your branch to get things passing for Composer v1 and v2.

Notably, I removed some of the tooling I had in the root `composer.json`. It's not necessarily important to maintaining this repository, so it's not a big deal to me to remove it, especially since it makes testing easier.

I also removed `--no-check-version` from the `validate` command. While `version` is command to find in `package.json`, I've never seen anyone put `version` in their `composer.json` file, so I think the warning will be rare. If someone sees failures due to these warnings, I hope they'll open an issue here, and we can address it then.

**Review by ramsey — APPROVED** [review]

**Comment by jrfnl** [comment]
> I took the liberty of making some changes to your branch to get things passing for Composer v1 and v2.

Thanks for that!

> Notably, I removed some of the tooling I had in the root `composer.json`. It's not necessarily important to maintaining this repository, so it's not a big deal to me to remove it, especially since it makes testing easier.

If you like, you could add a  GHA job to at least run `composer-normalize` by [requesting it as a tool from `setup-php`](https://github.com/shivammathur/setup-php/#wrench-tools-support). Happy to set that up for you if you'd like that.

> I also removed `--no-check-version` from the `validate` command. While `version` is command to find in `package.json`, I've never seen anyone put `version` in their `composer.json` file, so I think the warning will be rare. If someone sees failures due to these warnings, I hope they'll open an issue here, and we can address it then.

I agree that will probably be rare, though I also have to admit that I ran into it again only the other week... (and removed it from that project: https://github.com/php-parallel-lint/PHP-Code-Style/commit/f1a82cb6152cf960b5369a5a58f736c7adc91064)

**Comment by jrfnl** [comment]
Heads up for other contributors: the removal of Captain Hook doesn't automatically "clean up" the hooks which were put in place in the `.git/hooks` folder. Those need to be manually removed as otherwise most every git operation will break on the now missing `captainhook.json` configuration.

**Comment by ramsey** [comment]
> If you like, you could add a GHA job to at least run composer-normalize by requesting it as a tool from setup-php. Happy to set that up for you if you'd like that.

Sounds good to me. Feel free to set it up, and thanks!

**Comment by jrfnl** [comment]
> > If you like, you could add a GHA job to at least run composer-normalize by requesting it as a tool from setup-php. Happy to set that up for you if you'd like that.
> 
> Sounds good to me. Feel free to set it up, and thanks!

While looking at the workflow, I saw some more tweaks which could (should) be made, so I've done a more extensive update. PR upcoming.

**Pull request merged**
