### PR TITLE
fix(composer-cache-dir): use working-directory input to get composer cache dir

### PR DESCRIPTION
**Pull request by Kocal**
Following of #58, #93 and maybe of https://github.com/ramsey/composer-install/issues/58#issuecomment-791889189. 

I totally forgot to use working-directory to get composer cache dir. 
Composer needs a `composer.json` in the working directory to works, otherwise it fails:
image

Ping @ramsey 

Thanks!

**EDIT:** see 2nd part of https://github.com/ramsey/composer-install/pull/104#issuecomment-794244901

### CODE REVIEW

**Comment by phanan** [comment]
Looks like the implementation of `working-directory` option indeed breaks. I'm wondering if we really need this option though. Knowing that `--working-dir` is just another option that Composer supports, why don't we just use the current `composer-options` e.g., `composer-options: --prefer-dist --working-dir=subdir`?

**Comment by Kocal** [comment]
Well that's what @OskarStark and @osteel already tried (see #58) but it didn't work.

**Comment by phanan** [comment]
I guess the ship has sailed, but IMHO we could've tried supporting the native option instead of introducing a non-standard one (and leaving the native one unsupported).

**Comment by ramsey** [comment]
The reason why `--working-directory` doesn't work as part of `composer-options` is because of what @Kocal discovered here: the `composer config cache-dir` command also needs `--working-directory` passed to it, and `composer-options` is only passed to the `composer install` command.

**Comment by phanan** [comment]
Can we somehow obtain the `--working-dir` option from `composer-options` and use it to resolve the cache dir? If I'm not making any sense, or if this should be another topic altogether, please let me know.

Edit: I see @Kocal is implementing more or less the same logic in this PR, but using the `working-directory` option.

**Comment by ramsey** [comment]
@phanan That makes sense, and I think it's a good idea.

**Comment by Kocal** [comment]
Well, I'm not a big fan for parsing arguments for `--working-dir` and its alias, while using a `working-directory` input makes everyone happy.

But yes that's off-topic about the pull request.

**Comment by ramsey** [comment]
> Well, I'm not a big fan for parsing arguments for `--working-dir` and its alias

Any particular reason why?

**Comment by Kocal** [comment]
I'm not a big fan because:
1. Parsing arguments is hard, there are a lot of syntaxes to support which also depends of the OS, e.g.:
  - `--working-dir subdirectory`  
  - `--working-dir "subdirectory"`  
  - `--working-dir 'subdirectory'`  
  - `--working-dir=subdirectory`  
  - `--working-dir="subdirectory"`  
  - `--working-dir='subdirectory'`
  - ...
2. We should also support alias `-d` 
3. Whenever a new major version of Composer decide to drop `--working-dir`/`-d` for another option, many users will have to update their CI, while the action could handle it automatically with `working-directory` input + composer version detection
4. I'm seeing this action as a "big wrapper" of Composer, and I prefer the action driving Composer instead of the opposite. 

The 1st and 2nd bullets can be solved by using a npm dependency, the 3rd and 4th... honestly I care about those details but not at the point "I won't stop using your action". I won't care about how the implementation is made as long I can use the action in a sub-project.

**Comment by ramsey** [comment]
@Kocal All of these are great points.

I do think @phanan's idea is probably a more *natural* way of configuring Composer. That is, it's more intuitive to pass the arguments than to look for another property. Many folks might even try passing `--working-directory` in `composer-options` and not understand why it doesn't work properly.

This is starting to get way off-topic for this PR, but I think it's a good discussion.

The reason `composer config` requires `--working-directory` is because it expects a `composer.json` to exist in the current working directory. However, when running `composer config` with `--global`, it doesn't need to know where `composer.json` is. If we switch to use `composer config --global cache-dir`, does this solve the `working-directory` issue?

**Comment by Kocal** [comment]
That's true, you would expect to use the action with any Composer options and parsing `--working-dir` would be fine. 

> If we switch to use `composer config --global cache-dir`, does this solve the `working-directory` issue?

Yes that's working too! Good job, I didn't think about this.

I'm gonna update the code and tests soon.

**Comment by ramsey** [comment]
Great! Thanks!

**Comment by Kocal** [comment]
@ramsey the PR has been rebased + updated for using `composer --global`.
The options parsing will be done in another PR.

I've also fixed a bug with `hashFiles()` call where the working directory was not used, resulting the hash was the same between root and a subdirectory:
image
image

Now it gives:
image
image

**Comment by ramsey** [comment]
Great catch regarding `hashFiles()`!

Thanks for submitting this!

**Pull request merged**
