### PR TITLE
Fix race condition

### LINKED ISSUE #152: Cache restore race condition?
Hey there 👋🏻 , thank you for this action! It makes my workflows (and thus) life much easier than having to deal with Composer and `actions/cache` myself.

However, I did a few test runs and noticed that I get failures every now and then, let's say in 1 out of 5 workflow runs. Those failures are transient and most of the time go away if I run the workflow again.

The bottom line error message is 

```
2021-06-09T05:51:45.7317484Z ##[error]Failed to execute git clone --mirror -- 'ssh://git@github.com/MYORG/MYORG-SOME-PRIVATE-REPO' '/home/runner/.cache/composer/vcs/ssh---git-github.com-MYORG-MYORG-SOME-PRIVATE-REPO/'

Cloning into bare repository '/home/runner/.cache/composer/vcs/ssh---git-github.com-MYORG-MYORG-SOME-PRIVATE-REPO'...
BUG: refs/files-backend.c:2953: initial ref transaction called with existing refs
Aborted (core dumped)
```

Unfortunately, the Composer dependency in question is for a private repo that will be `git`-cloned as `source`, and I can't share all the details. But here is an excerpt from the raw logs with what I think is relevant.

```
2021-06-09T05:51:23.2825442Z ##[group]Operating System
2021-06-09T05:51:23.2827149Z Ubuntu
2021-06-09T05:51:23.2828278Z 18.04.5
2021-06-09T05:51:23.2829465Z LTS
2021-06-09T05:51:23.2830596Z ##[endgroup]
2021-06-09T05:51:23.2831828Z ##[group]Virtual Environment
2021-06-09T05:51:23.2833168Z Environment: ubuntu-18.04
2021-06-09T05:51:23.2834390Z Version: 20210531.0
2021-06-09T05:51:23.2837061Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20210531.0/images/linux/Ubuntu1804-README.md
2021-06-09T05:51:23.2839459Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20210531.0
2021-06-09T05:51:23.2841153Z ##[endgroup]
...
2021-06-09T05:51:40.1782268Z ##[group]Run ramsey/composer-install@v1
2021-06-09T05:51:40.1783292Z with:
2021-06-09T05:51:40.1784197Z   dependency-versions: locked
2021-06-09T05:51:40.1785094Z env:
2021-06-09T05:51:40.1785850Z   APP_ENV: test
2021-06-09T05:51:40.1786845Z   PHP_VERSION: 7.2
2021-06-09T05:51:40.1787798Z   SSH_AUTH_SOCK: /tmp/ssh-MZQQ7o4xWr9F/agent.2587
2021-06-09T05:51:40.1789259Z   SSH_AGENT_PID: 2588
2021-06-09T05:51:40.1790655Z   TEMP: /home/runner/work/MYREPO/MYREPO/tmp
2021-06-09T05:51:40.1793996Z   COMPOSER_AUTH: ***
2021-06-09T05:51:40.1794829Z ##[endgroup]
2021-06-09T05:51:40.5953452Z Composer cache directory found at /home/runner/.cache/composer
2021-06-09T05:51:40.5977780Z Composer working directory set to project root.
2021-06-09T05:51:40.5981742Z Using locked versions of dependencies
2021-06-09T05:51:40.6680768Z PHP version is 7.2.34-21+ubuntu18.04.1+deb.sury.org+1
2021-06-09T05:51:40.6682462Z Operating system is linux
2021-06-09T05:51:40.6686362Z Cache primary key is linux-php-7.2.34-21+ubuntu18.04.1+deb.sury.org+1-locked-82ffafb70b7e4a023b19b2e8ef1eef08eb2e61b31dd27e40b751819a7f8331fe-
2021-06-09T05:51:40.6693769Z Cache restore keys are: linux-php-7.2.34-21+ubuntu18.04.1+deb.sury.org+1-locked-82ffafb70b7e4a023b19b2e8ef1eef08eb2e61b31dd27e40b751819a7f8331fe-, linux-php-7.2.34-21+ubuntu18.04.1+deb.sury.org+1-locked-
2021-06-09T05:51:40.7612805Z [command]/usr/local/bin/composer install --no-interaction --no-progress --ansi
2021-06-09T05:51:40.9632982Z  Installing dependencies from lock file (including require-dev) 
2021-06-09T05:51:40.9751962Z  Verifying lock file contents can be installed on current platform. 
2021-06-09T05:51:42.4208308Z Received 0 of 49209747 (0.0%), 0.0 MBs/sec
2021-06-09T05:51:42.6212086Z  Package operations: 186 installs, 0 updates, 0 removals 
2021-06-09T05:51:42.6217458Z   - Downloading  composer/package-versions-deprecated  ( 1.11.99.2 )
2021-06-09T05:51:42.6228500Z   - Downloading  symfony/polyfill-mbstring  ( v1.23.0 )
... a lot of "Downloading ..." dist files ...
2021-06-09T05:51:42.6460638Z   - Syncing  MYORG/SOME-PRIVATE-REPO  ( 3.1.0 ) into cache
2021-06-09T05:51:43.0227542Z Received 49209747 of 49209747 (100.0%), 29.3 MBs/sec
2021-06-09T05:51:43.0228762Z Cache Size: ~47 MB (49209747 B)
2021-06-09T05:51:43.0267378Z [command]/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/1c4b8074-9a05-4165-8e57-9b97c3c0e543/cache.tzst -P -C /home/runner/work/MYREPO/MYREPO
2021-06-09T05:51:43.1632026Z Cache restored successfully
2021-06-09T05:51:43.1746121Z Cache restored from key: linux-php-7.2.34-21+ubuntu18.04.1+deb.sury.org+1-locked-bac6c14ffff580a04a4fea1394e68aa862bb682755fbc9d2277682591500a408-
2021-06-09T05:51:45.7317484Z ##[error]Failed to execute git clone --mirror -- 'ssh://git@github.com/MYORG/MYORG-SOME-PRIVATE-REPO' '/home/runner/.cache/composer/vcs/ssh---git-github.com-MYORG-MYORG-SOME-PRIVATE-REPO/'

Cloning into bare repository '/home/runner/.cache/composer/vcs/ssh---git-github.com-MYORG-MYORG-SOME-PRIVATE-REPO'...
BUG: refs/files-backend.c:2953: initial ref transaction called with existing refs
Aborted (core dumped)

2021-06-09T05:51:45.7333789Z 
2021-06-09T05:51:45.7538921Z  [37;41m                                                                                                                                                                                            [39;49m
2021-06-09T05:51:45.7541852Z  [37;41m  [RuntimeException]                                                                                                                                                                        [39;49m
2021-06-09T05:51:45.7545887Z  [37;41m  Failed to execute git clone --mirror -- 'ssh://git@github.com/MYORG/MYORG-SOME-PRIVATE-REPO' '/home/runner/.cache/composer/vcs/ssh---git-github.com-MYORG-MYORG-SOME-PRIVATE-REPO/'   [39;49m
2021-06-09T05:51:45.7549415Z  [37;41m                                                                                                                                                                                            [39;49m
2021-06-09T05:51:45.7552153Z  [37;41m  Cloning into bare repository '/home/runner/.cache/composer/vcs/ssh---git-github.com-MYORG-MYORG-SOME-PRIVATE-REPO'...                                                                   [39;49m
2021-06-09T05:51:45.7556156Z  [37;41m  BUG: refs/files-backend.c:2953: initial ref transaction called with existing refs                                                                                                         [39;49m
2021-06-09T05:51:45.7558622Z  [37;41m  Aborted (core dumped)                                                                                                                                                                     [39;49m
2021-06-09T05:51:45.7561683Z  [37;41m                                                                                                                                                                                            [39;49m
```

What strikes me is the way how

```
2021-06-09T05:51:43.1632026Z Cache restored successfully
2021-06-09T05:51:43.1746121Z Cache restored from key: linux-php-7.2.34-21+ubuntu18.04.1+deb.sury.org+1-locked-bac6c14ffff580a04a4fea1394e68aa862bb682755fbc9d2277682591500a408-
```

happens just before the error, and how that is interleaved with the actual Composer run.

So, my suspicion is that some async operations go wrong here, so that the cache is restored while Composer is already running. Maybe that does not make much of a difference for `dist` files, but might be enough to make `git` stumble when it runs on a partly-restored repo?

I should also add that I have some concurrent workflows that run this action here at about the same time. But to my knowledge, different workflows run in isolated environments. So I would rule out any kind of cross-workflow race conditions.

### LINKED ISSUE #161: Failed to extracting archive when use parallel jobs with ramsey/composer-install@v1
```workflow
name: Run tests and deploy

on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
      - '**.js'
      - '**.json'
      - '**.xml'
      - 'composer.*'
      - '.github/workflows/main.yml'

jobs:

  test_php:
    name: Run PHP tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: bcmath, curl, dom, filter, gd, hash, intl, json, libxml, mbstring, openssl, pdo_mysql, pdo, redis, simpleXML
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist --no-scripts"


  check_php_syntax:
    name: Check PHP syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: bcmath, curl, dom, filter, gd, hash, intl, json, libxml, mbstring, openssl, pdo_mysql, pdo, redis, simpleXML
          tools: cs2pr
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist --no-scripts"
```

```
Failed to extract square1/nova-metrics: (9) '/usr/bin/unzip' -qq '/home/runner/work/REPO-NAME/REPO-NAME/vendor/composer/tmp-887e5e92dba4429f8f1bb7ee187d3e61' -d '/home/runner/work/REPO-NAME/REPO-NAME/vendor/composer/344f5f96'

[/home/runner/work/REPO-NAME/REPO-NAME/vendor/composer/tmp-887e5e92dba4429f8f1bb7ee187d3e61]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/runner/work/REPO-NAME/REPO-NAME/vendor/composer/tmp-887e5e92dba4429f8f1bb7ee187d3e61 or
        /home/runner/work/REPO-NAME/REPO-NAME/vendor/composer/tmp-887e5e92dba4429f8f1bb7ee187d3e61.zip, and cannot find /home/runner/work/REPO-NAME/REPO-NAME/vendor/composer/tmp-887e5e92dba4429f8f1bb7ee187d3e61.ZIP, period.

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
    Install of square1/nova-metrics failed
Error: '/home/runner/work/REPO-NAME/REPO-NAME/vendor/composer/tmp-887e5e92dba4429f8f1bb7ee187d3e61' is not a zip archive.
```

### PR DESCRIPTION
**Pull request by olivernybroe**
I think I might have found the reason for the race condition. 
So looking at the following script https://github.com/actions/cache/blob/main/src/restore.ts it executes an promise, but doesn't return it.

We however require this script and treats it as if it were a promise, but the script doesn't give us a promise back. so we do an await on nothing basically. 

To fix this, I chose to use the github action caching api directly, instead of executing the github caching actions script directly. This means we now get a Promise back and we actually have something we can wait on. 

I reran this around 20 times on our repository to try and reproduce the error (we got this error like every 5 times) and it seems to be gone now. 

I have put it live on our repository and will run with our branch for a week or so before taking this PR out of draft 👍 

for people who wanna try out our solution and test it with us, you can use it the following way
```yaml
      - name: Install Composer dependencies
        uses: worksome/composer-install@fix-race-condition
```

resolves: #161
resolves: #152

### CODE REVIEW

**Comment by ramsey** [comment]
This is great! Thanks!

I've put out a call on Twitter to ask folks who use this to test your changes. https://twitter.com/ramsey/status/1459190635479674884

**Comment by Lewiscowles1986** [comment]
It reads a lot better and seems like it works.

The logic makes sense; however there is no test case for the await on nothing. No synthetic crash reproduction. So if it works, the breakage is not documented anywhere; just fixed. This will make it harder to re-factor and avoid regression.

I think if https://stackoverflow.com/a/55263084/1548557 is correct, then await will first check if something has a `then` method. Do you think checking for the presence of this for all cases would help?

Secondly, having a then Clause won't guarantee something returns a response. So you could also check the value of the awaited result, ensuring it is never null or undefined (perhaps using `??` with a known bad value so it's explicit and readable?

What do you think?

**Comment by olivernybroe** [comment]
@Lewiscowles1986 I agree, this could really use a test case for making sure the scenario is not added back in later. 

> however there is no test case for the await on nothing.

I tried creating it when I wrote my PR, but simply couldn't get the mockery library to do as I wanted so I just said "fuck it". 
I simply do not know typescript, and didn't feel like spending more time on this PR. Would appreciate help on this part.

> Do you think checking for the presence of this for all cases would help?

Yes, I do think that would be a good idea. However linting should fail if what is given is not a promise. This is why I changed the typehints to be correct and require promises in the typehints. This way linting would complain when non-promises are used here. Do you think that is enough or where you envisioning something more?

> So you could also check the value of the awaited result, ensuring it is never null or undefined

Hmm, that might be possible, as the cache functions do have some return values. However we do now have typehints requiring them to return that type. so in theory linting should catch it ;) 


Thanks a lot for the feedback and trying to also do the research to figure out if this indeed is a solution

**Comment by Lewiscowles1986** [comment]
Await on no test would look something like

```
it('should always return a promise', async () => {
    const result = await Promise.resolve(/* call to method not returning a promise that should */);
    expect(result).toBeTruthy();
});
```

TypeScript may be a complicating factor in this though. I've hit this a few times where I basically had to move a TypeScript project to JS because valid typescript with all it's supposed protections; prevented me from testing behavior that could be measured after transpiling to JS.

Maybe someone else has a tip I'm unaware of if this doesn't work.

Specifically that should fail for `master`, but pass for your branch.

**Comment by olivernybroe** [comment]
So I think we can safely say that the solution here is working. 
We have had no errors of the race condition in a whole week 👍 

However @Lewiscowles1986 does have a valid point that we are missing test for it. However if I have to create the test it will take a while. 
So I'll let @ramsey choose here, if they either can get someone else to do the test, do it themselves, or if they will merge it in without any test.

**Comment by kevinpapst** [comment]
This issue causes (only for me) at least once a day a failed build / the need to manually trigger "rebuild all". 

As there is no test yet that fails even though there is a problem for at least some users, I'd argue that fixing the issue is more important than waiting for a test case for code which wasn't covered before.
Or in other words: this workflow is more or less "feature complete", so do you really expect that this problem will be reintroduced in the future? I don't see that many changes in the last year and no real need for in the future.

There is another question that I'd like to raise: should the dist files be included in the merge (good for testing) or rather being rebuild after merged by the repo maintainer (the user base trusts this repo)?

**Comment by ruudk** [comment]
I agree, I also stumble on this multiple times per week on different repositories.

**Comment by olivernybroe** [comment]
@kevinpapst Agreed, I also agree that when/if this is being merged by @ramsey, he should rebuild it, so it's not my dist files 👍

**Comment by ruudk** [comment]
@ramsey Would it be possible to merge this? 🙏

**Comment by kevinpapst** [comment]
@ramsey this is open source, it is your right to ignore our problems here. but I want to try it once again: could you please be so kind and share your plans about this topic. I am hitting that re-run all jobs literally every day and this last one was once too often 😁 I just want to know if we have a chance that this will be integrated and released anytime soon or if it is better that we are setting up our own forks of the action?

**Comment by ramsey** [comment]
@kevinpapst I've been waiting to see if @olivernybroe or anyone else would provide a test. You're welcome to run the action from your own fork.

**Comment by kevinpapst** [comment]
Thanks for your feedback @ramsey, and thanks for your action. It solves a problem for a certain target group in a neat way.
But as parallel builds are a problem and all my projects use matrix build I cannot wait any longer for a fix that exist but does not get merged.

For anyone interested, you can use the cache action combined with the speed improvements from Composer 2 to get the same build times (I could not see any speed difference to this action here). 

All you have to do is to replace:
```
            -    name: Install dependencies
                 uses: ramsey/composer-install@v1
```
with
```
            -   name: Determine composer cache directory
                id: composer-cache
                run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

            -   name: Cache Composer dependencies
                uses: actions/cache@v2
                with:
                    path: "${{ steps.composer-cache.outputs.directory }}"
                    key: ${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

            -   name: Install dependencies
                run: composer install
```

**Comment by Lewiscowles1986** [comment]
@ramsey I've not been able to recreate a race in local tests. This is my key reason for not attempting a test.

While I understand this might be frustrating, I think it's a wise choice to hold-off until we can make a reproductive case test, and then it can be confirmed why the flakes, and how they were fixed.

**Comment by ramsey** [comment]
GitHub now [supports `uses` on steps in a composite action](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsuses). They did not support this when I began developing this action, which is why I had to develop it as a JavaScript action.

Since I'm now able to develop this as a composite action, I've shifted away from JavaScript and have converted this to a composite action in `v2`.

As a side note: when I first began developing this, GitHub's cache action also was not a separate library intended for use by other actions. They've since changed this, as well, so if I couldn't switch to a composite action, I would have updated to the latest version of their library, which might have fixed this race condition, among other issues.

Now that I'm using GitHub's cache action directly as part of a composite action, I think any of the race conditions and inability to read cache files that folks were experiencing (due to my bad JavaScript code) should be cleared up.

Please upgrade using `ramsey/composer-install@v2` or `ramsey/composer-install@2.0.0`. Details are available on the [release announcement](https://github.com/ramsey/composer-install/releases/tag/2.0.0) and the [README](https://github.com/ramsey/composer-install/tree/v2#readme).

Thanks for your PR and the good discussion here that encouraged me to make this change!

**Comment by olivernybroe** [comment]
@ramsey amazing! Looking forward to changing to version 2 🎉 

Thanks for the work to change this to a composite action!

**Pull request closed without merging**
